version: '3.8'

services:
  app:
    build: .  # Build the image from the Dockerfile in the current directory
    working_dir: /app  # Set the working directory inside the container
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "${HOST_PORT:+$HOST_PORT:3000}"  # Map port 3000 of the container to port defined by HOST_PORT env variable, if defined
    env_file:
      - .env  # Load environment variables from the .env file